### ISSUE TITLE
sampleMat() producing inconsistent sample sizes

### ISSUE THREAD

**Issue by grahamfrank** [bbolker/betararef#2]
I'm having trouble getting the sampleMat() function to produce random samples of the sizes specified by the n.target argument for all rows in a community matrix. For some reason, it produces the correct sample sizes for some rows, but for others will just return the original values. Below is my best attempt at a reproducible example. 

comm <- data.frame(matrix(ncol=4, nrow=5))
set.seed(625)
for(i in 1:5){
  comm[i,] <- round(rpois(n = 4, lambda=3),digits = 0)
}
m.vec <- c(5,8,4,4,6)
comm.raref<-sampleMat(comm, n.target = m.vec)
rowSums(comm.raref)==m.vec

**Comment by bbolker** [comment]
Hmm.  I'm glad someone is using this code! I'll try to take a look.

**Comment by grahamfrank** [comment]
I think I found the issue. Line 130 of Rarefaction_funs.R 
  if (n.target==length(xmat)) return(xmat)  ## don't really rarefy

This returns the original assemblage if the number of _species_ is equal to the n.target, whereas I think the goal is to return the original assemblage if the number of _individuals_ is equal to n.target. 

I was able to fix the problem by changing the line to 
  if (n.target==length(spvec)) return(xmat)

**Comment by bbolker** [comment]
thank you!  should be fixed in the source now ...
